development:
  domain: localhost:3000
  email_accounts_alert_pw: (drz%1%X*Cwo
  email_accounts_alert_un: alert+traydr.com
  email_server_outgoing_hostname: mail.traydr.com
  email_server_outgoing_port: 26
  email_server_outgoing_from_hostname: traydr.com
  email_server_outgoing_welcome_from_un: welcome
  email_server_outgoing_alert_from_un: alert

test:
  domain: test.host

production:
  domain: traydr.com
